### ISSUE TITLE
Inference and return error: AttributeError: 'LlavaConfig' object has no attribute 'X'

### ISSUE THREAD

**Issue by lognat0704** [llyx97/TempCompass#2]
Hi. Thanks for the sharing. I am tyring to install and do inference when do the inference 

`python inference_dataset.py --task_type yes_no`

 I encouter the following error:

```
Traceback (most recent call last):
  File "/home/nelson/TempCompass/run_video_llava/inference_dataset.py", line 84, in <module>
    tokenizer, model, processor, context_len = load_pretrained_model(model_path, None, model_name, load_8bit, load_4bit, device=device)
  File "/home/nelson/TempCompass/run_video_llava/llava/model/builder.py", line 142, in load_pretrained_model
    X = model.config.X
  File "/home/nelson/TempCompass/tempcompassvenv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 261, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'LlavaConfig' object has no attribute 'X'
```

Looks I need to install the proper transformer version. Could you share which transformer version you used for the project?

Best,

**Comment by llyx97** [comment]
Thanks for bringing this issue to our attention.
I think this is caused by an update made in https://huggingface.co/LanguageBind/Video-LLaVA-7B/blob/main/config.json
Please replace the config.json in `LanguageBind/Video-LLaVA-7B` with this [file](https://github.com/llyx97/TempCompass/blob/main/run_video_llava/config.json).
(My transformers version is 4.31.0)

**Comment by lognat0704** [comment]
Thx. it works.

**Comment by lognat0704** [comment]
Thx. it works
